import * as vscode from 'vscode';
import { ConnectionManager } from '../core/manager';
import { errorMessage, logError } from '../core/log';
import { isDestructiveSql, splitSqlStatements, sqlString, statementAtOffset } from '../core/util';
import { runSqlAndShow } from './sqlRunner';
import { escapeHtml, nonce } from './webviewUtil';

const HISTORY_KEY = 'vanthrex.sqlHistory';
const SAVED_KEY = 'vanthrex.savedQueries';
interface SavedQuery { name: string; sql: string }

type ObjArg = { library: string; name: string; type?: string };

// ---------------------------------------------------------------- generate DDL

async function generateDdl(manager: ConnectionManager, o: ObjArg): Promise<void> {
  const conn = manager.require();
  if (!conn.sqlKeepsJob) {
    throw new Error('Generate SQL needs the Mapepire SQL engine (it reads the result from QTEMP). Change the SQL engine in the connection settings.');
  }
  const t = await conn.rows<{ T: string }>(
    `SELECT TABLE_TYPE AS T FROM QSYS2.SYSTABLES WHERE SYSTEM_TABLE_SCHEMA = ${sqlString(o.library)} AND SYSTEM_TABLE_NAME = ${sqlString(o.name)}`, 1);
  const tableType = String(t[0]?.T ?? '').trim();
  // T = SQL table, P = physical file, V = view, L = logical file, M = MQT, A = alias.
  const candidates = tableType === 'V' ? ['VIEW'] : tableType === 'L' ? ['VIEW', 'INDEX'] : tableType === 'A' ? ['ALIAS']
    : tableType ? ['TABLE'] : ['TABLE', 'VIEW', 'INDEX', 'PROCEDURE', 'FUNCTION', 'TRIGGER', 'SEQUENCE'];
  let lines: string[] = [];
  let lastError = '';
  for (const kind of candidates) {
    try {
      const res = await conn.sql(
        `CALL QSYS2.GENERATE_SQL(DATABASE_OBJECT_NAME => ${sqlString(o.name)}, DATABASE_OBJECT_LIBRARY_NAME => ${sqlString(o.library)}, ` +
        `DATABASE_OBJECT_TYPE => '${kind}', CREATE_OR_REPLACE_OPTION => '1', PRIVILEGES_OPTION => '0')`, 100000);
      lines = res.rows.map(r => String(r.SRCDTA ?? Object.values(r).pop() ?? ''));
      if (!lines.length) {
        const q = await conn.rows<{ SRCDTA: string }>('SELECT SRCDTA FROM QTEMP.Q_GENSQL ORDER BY SRCSEQ', 100000);
        lines = q.map(r => String(r.SRCDTA ?? ''));
      }
      if (lines.length) { break; }
    } catch (e) { lastError = errorMessage(e); }
  }
  if (!lines.length) { throw new Error(`Could not generate SQL for ${o.library}/${o.name}${lastError ? `: ${lastError}` : '.'}`); }
  const doc = await vscode.workspace.openTextDocument({
    language: 'sql',
    content: `-- Generated by QSYS2.GENERATE_SQL for ${o.library}/${o.name}\n` + lines.map(l => l.replace(/\s+$/, '')).join('\n') + '\n',
  });
  await vscode.window.showTextDocument(doc);
}

// ---------------------------------------------------------------- run a whole script

interface StepResult { sql: string; ok: boolean; ms: number; rows: number; columns: string[]; data: unknown[][]; message: string }

class ScriptPanel {
  private static panel?: vscode.WebviewPanel;
  static show(title: string, steps: StepResult[], running: boolean): void {
    if (!ScriptPanel.panel) {
      ScriptPanel.panel = vscode.window.createWebviewPanel('vanthrex.sqlScript', title,
        { viewColumn: vscode.ViewColumn.Beside, preserveFocus: true }, { enableScripts: true });
      ScriptPanel.panel.onDidDispose(() => { ScriptPanel.panel = undefined; });
    }
    ScriptPanel.panel.title = title;
    const n = nonce();
    const ok = steps.filter(s => s.ok).length;
    const body = steps.map((s, i) => {
      const table = s.columns.length
        ? `<table><tr>${s.columns.map(c => `<th>${escapeHtml(c)}</th>`).join('')}</tr>` +
          s.data.map(r => `<tr>${r.map(v => `<td>${v === null || v === undefined ? '<i>null</i>' : escapeHtml(String(v))}</td>`).join('')}</tr>`).join('') + '</table>'
        : '';
      return `<details ${!s.ok || (i === steps.length - 1 && s.columns.length) ? 'open' : ''}><summary class="${s.ok ? 'ok' : 'bad'}">` +
        `${s.ok ? '✔' : '✖'} <b>${i + 1}.</b> <code>${escapeHtml(s.sql.replace(/\s+/g, ' ').slice(0, 140))}</code> ` +
        `<span class="dim">${escapeHtml(s.message)} · ${s.ms} ms</span></summary>${table}</details>`;
    }).join('');
    ScriptPanel.panel.webview.html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${n}';">
<style>
 body { font-family: var(--vscode-font-family); color: var(--vscode-foreground); padding: 8px 12px; }
 summary { cursor: pointer; padding: 4px 0; } .ok { } .bad { color: var(--vscode-errorForeground); }
 .dim { color: var(--vscode-descriptionForeground); } code { font-family: var(--vscode-editor-font-family); }
 table { border-collapse: collapse; margin: 6px 0 12px 18px; font-family: var(--vscode-editor-font-family); font-size: var(--vscode-editor-font-size); }
 th, td { border: 1px solid var(--vscode-editorWidget-border, #8883); padding: 2px 8px; text-align: left; white-space: pre; }
 th { background: var(--vscode-editorWidget-background); }
</style></head><body>
<p><b>${running ? 'Running…' : 'Finished'}</b> — ${ok} of ${steps.length} statement(s) succeeded${steps.length - ok ? `, ${steps.length - ok} failed` : ''}.</p>
${body}</body></html>`;
  }
}

async function runScript(manager: ConnectionManager): Promise<void> {
  const conn = manager.require();
  const editor = vscode.window.activeTextEditor;
  if (!editor || editor.document.languageId !== 'sql') { throw new Error('Open a .sql file (or the SQL scratchpad) first.'); }
  const text = editor.selection.isEmpty ? editor.document.getText() : editor.document.getText(editor.selection);
  const statements = splitSqlStatements(text).map(s => s.sql);
  if (!statements.length) { throw new Error('No SQL statements found.'); }
  const cfg = vscode.workspace.getConfiguration('vanthrex');
  const risky = statements.filter(isDestructiveSql);
  if (cfg.get<boolean>('sql.confirmDestructive', true) && risky.length) {
    const ok = await vscode.window.showWarningMessage(
      `${risky.length} of the ${statements.length} statements can change or remove a lot of data (DROP, TRUNCATE, DELETE/UPDATE without WHERE). Run the script?`,
      { modal: true }, 'Run Script');
    if (ok !== 'Run Script') { return; }
  }
  const stopOnError = cfg.get<boolean>('sql.scriptStopOnError', true);
  const maxRows = Math.min(cfg.get<number>('sql.maxRows', 500), 200);
  const steps: StepResult[] = [];
  const title = `SQL Script (${statements.length})`;
  await vscode.window.withProgress({ location: vscode.ProgressLocation.Notification, title: 'Running SQL script', cancellable: true }, async (progress, token) => {
    for (const [i, sql] of statements.entries()) {
      if (token.isCancellationRequested) { break; }
      progress.report({ message: `${i + 1} of ${statements.length}`, increment: 100 / statements.length });
      const started = Date.now();
      try {
        const r = await conn.sql(sql, maxRows);
        steps.push({
          sql, ok: true, ms: Date.now() - started, rows: r.rows.length, columns: r.columns,
          data: r.rows.map(row => r.columns.map(c => row[c] ?? null)),
          message: r.columns.length ? `${r.rows.length}${r.truncated ? '+' : ''} row(s)` : r.updateCount >= 0 ? `${r.updateCount} row(s) affected` : 'done',
        });
      } catch (e) {
        logError(e);
        steps.push({ sql, ok: false, ms: Date.now() - started, rows: 0, columns: [], data: [], message: errorMessage(e) });
        ScriptPanel.show(title, steps, true);
        if (stopOnError) { break; }
      }
      ScriptPanel.show(title, steps, true);
    }
  });
  ScriptPanel.show(title, steps, false);
}

// ---------------------------------------------------------------- history & saved queries

function currentStatement(): string | undefined {
  const editor = vscode.window.activeTextEditor;
  if (!editor || editor.document.languageId !== 'sql') { return undefined; }
  return (editor.selection.isEmpty
    ? statementAtOffset(editor.document.getText(), editor.document.offsetAt(editor.selection.active))
    : editor.document.getText(editor.selection))?.trim().replace(/;\s*$/, '');
}

async function useStatement(manager: ConnectionManager, state: vscode.Memento, sql: string): Promise<void> {
  const pick = await vscode.window.showQuickPick([
    { label: '$(play) Run it', id: 'run' },
    { label: '$(go-to-file) Open in a new SQL editor', id: 'open' },
    { label: '$(insert) Insert at the cursor', id: 'insert' },
    { label: '$(clippy) Copy', id: 'copy' },
  ], { title: sql.replace(/\s+/g, ' ').slice(0, 100) });
  if (!pick) { return; }
  if (pick.id === 'run') { return runSqlAndShow(manager, state, sql); }
  if (pick.id === 'copy') { await vscode.env.clipboard.writeText(sql); return; }
  const editor = vscode.window.activeTextEditor;
  if (pick.id === 'insert' && editor) {
    await editor.edit(e => e.insert(editor.selection.active, sql.endsWith(';') ? sql : sql + ';'));
    return;
  }
  const doc = await vscode.workspace.openTextDocument({ language: 'sql', content: sql + ';\n' });
  await vscode.window.showTextDocument(doc);
}

export function registerSqlTools(context: vscode.ExtensionContext, manager: ConnectionManager): void {
  const state = context.globalState;
  const guard = <A extends unknown[]>(fn: (...a: A) => Promise<unknown>) => async (...a: A) => {
    try { await fn(...a); } catch (e) { vscode.window.showErrorMessage(errorMessage(e)); }
  };
  context.subscriptions.push(
    vscode.commands.registerCommand('vanthrex.generateDdl', guard(async (n?: ObjArg) => {
      let o = n?.library && n.name ? n : undefined;
      if (!o) {
        const v = await vscode.window.showInputBox({ title: 'Generate SQL (DDL)', prompt: 'LIBRARY/TABLE, view, index, procedure or function', placeHolder: 'MYLIB/CUSTMAST' });
        if (!v?.includes('/')) { return; }
        const [library, name] = v.trim().toUpperCase().split('/');
        o = { library, name };
      }
      await vscode.window.withProgress({ location: vscode.ProgressLocation.Notification, title: `Generating SQL for ${o.library}/${o.name}…` },
        () => generateDdl(manager, o!));
    })),
    vscode.commands.registerCommand('vanthrex.runSqlScript', guard(() => runScript(manager))),
    vscode.commands.registerCommand('vanthrex.sqlHistory', guard(async () => {
      const history = state.get<string[]>(HISTORY_KEY, []);
      if (!history.length) { vscode.window.showInformationMessage('No SQL history yet. Statements you run with Ctrl+Enter appear here.'); return; }
      const qp = vscode.window.createQuickPick<vscode.QuickPickItem & { sql: string }>();
      qp.title = 'SQL history (most recent first)';
      qp.matchOnDetail = true;
      qp.items = history.map(h => ({ label: h.replace(/\s+/g, ' ').slice(0, 120), sql: h, buttons: [{ iconPath: new vscode.ThemeIcon('star-empty'), tooltip: 'Save this query' }] }));
      qp.onDidTriggerItemButton(async e => {
        qp.hide();
        await vscode.commands.executeCommand('vanthrex.saveQuery', e.item.sql);
      });
      qp.onDidAccept(() => { const it = qp.selectedItems[0]; qp.hide(); if (it) { useStatement(manager, state, it.sql).catch(err => vscode.window.showErrorMessage(errorMessage(err))); } });
      qp.onDidHide(() => qp.dispose());
      qp.show();
    })),
    vscode.commands.registerCommand('vanthrex.clearSqlHistory', guard(async () => {
      const ok = await vscode.window.showWarningMessage('Clear the SQL history?', { modal: true }, 'Clear');
      if (ok) { await state.update(HISTORY_KEY, []); }
    })),
    vscode.commands.registerCommand('vanthrex.saveQuery', guard(async (preset?: string) => {
      const sql = typeof preset === 'string' ? preset : currentStatement();
      if (!sql) { throw new Error('Put the cursor in a SQL statement (or select it) first.'); }
      const name = await vscode.window.showInputBox({ title: 'Save query', prompt: 'Name for this query', value: sql.replace(/\s+/g, ' ').slice(0, 40), ignoreFocusOut: true });
      if (!name?.trim()) { return; }
      const saved = state.get<SavedQuery[]>(SAVED_KEY, []).filter(q => q.name !== name.trim());
      await state.update(SAVED_KEY, [...saved, { name: name.trim(), sql }].sort((a, b) => a.name.localeCompare(b.name)));
      vscode.window.setStatusBarMessage(`$(star-full) Saved query "${name.trim()}"`, 4000);
    })),
    vscode.commands.registerCommand('vanthrex.savedQueries', guard(async () => {
      const saved = state.get<SavedQuery[]>(SAVED_KEY, []);
      if (!saved.length) { vscode.window.showInformationMessage('No saved queries yet. Use "Vanthrex: Save Query" in a SQL editor, or the ☆ button in SQL History.'); return; }
      const qp = vscode.window.createQuickPick<vscode.QuickPickItem & { q: SavedQuery }>();
      qp.title = 'Saved queries';
      qp.matchOnDetail = true;
      qp.items = saved.map(q => ({ label: `$(star-full) ${q.name}`, detail: q.sql.replace(/\s+/g, ' ').slice(0, 160), q,
        buttons: [{ iconPath: new vscode.ThemeIcon('trash'), tooltip: 'Delete' }] }));
      qp.onDidTriggerItemButton(async e => {
        await state.update(SAVED_KEY, state.get<SavedQuery[]>(SAVED_KEY, []).filter(x => x.name !== e.item.q.name));
        qp.items = qp.items.filter(i => i.q.name !== e.item.q.name);
      });
      qp.onDidAccept(() => { const it = qp.selectedItems[0]; qp.hide(); if (it) { useStatement(manager, state, it.q.sql).catch(err => vscode.window.showErrorMessage(errorMessage(err))); } });
      qp.onDidHide(() => qp.dispose());
      qp.show();
    })),
  );
}
