// Short reference for RPG IV built-in functions and free-form operation codes, used for hovers & completion.

export interface DocEntry { syntax: string; summary: string; }

export const BIFS: Record<string, DocEntry> = {
  '%ABS': { syntax: '%ABS(numeric)', summary: 'Absolute value of a numeric expression.' },
  '%ADDR': { syntax: '%ADDR(variable {: *DATA})', summary: 'Address (pointer) of a variable. *DATA returns the address of the data of a varying field.' },
  '%ALLOC': { syntax: '%ALLOC(size)', summary: 'Allocate heap storage and return a pointer to it.' },
  '%CHAR': { syntax: '%CHAR(expression {: format})', summary: 'Convert a numeric, date, time, timestamp or UCS-2 value to character.' },
  '%CHECK': { syntax: '%CHECK(comparator : base {: start {: length}})', summary: 'Position of the first character in base that is NOT in comparator (0 if all match).' },
  '%CHECKR': { syntax: '%CHECKR(comparator : base {: start {: length}})', summary: 'Like %CHECK but scans from right to left.' },
  '%CONCAT': { syntax: '%CONCAT(separator : item1 : item2 ...)', summary: 'Concatenate values with a separator (IBM i 7.5+).' },
  '%DATE': { syntax: '%DATE({expression {: format}})', summary: 'Convert to a date value; with no parameters returns the current system date.' },
  '%DAYS': { syntax: '%DAYS(number)', summary: 'Number of days as a duration for date arithmetic, e.g. today + %DAYS(30).' },
  '%DEC': { syntax: '%DEC(expression {: digits : decimals})', summary: 'Convert to packed decimal. Also converts character, date and time values.' },
  '%DECH': { syntax: '%DECH(expression : digits : decimals)', summary: 'Convert to packed decimal with half-adjust (rounding).' },
  '%DIFF': { syntax: '%DIFF(op1 : op2 : unit {: frac})', summary: 'Difference between two dates/times/timestamps in *DAYS, *MONTHS, *YEARS, *HOURS, *MINUTES, *SECONDS, *MSECONDS.' },
  '%DIV': { syntax: '%DIV(n : m)', summary: 'Integer quotient of n divided by m.' },
  '%EDITC': { syntax: "%EDITC(numeric : editcode {: *ASTFILL | *CURSYM | currency})", summary: 'Format a number with an edit code (e.g. J, Z, X).' },
  '%EDITW': { syntax: '%EDITW(numeric : editword)', summary: 'Format a number with an edit word.' },
  '%ELEM': { syntax: '%ELEM(array | table | multiple-occurrence DS)', summary: 'Number of elements (dimension) of an array, table or DS. Use %ELEM(arr : *ALLOC/*MAX/*KEEP) for varying-dimension arrays.' },
  '%EOF': { syntax: '%EOF({file})', summary: '*ON if the last READ/READE/READP/READC… reached end of file.' },
  '%EQUAL': { syntax: '%EQUAL({file})', summary: '*ON if the last SETLL found an exact match, or LOOKUP found an equal element.' },
  '%ERROR': { syntax: '%ERROR()', summary: '*ON if the last operation with the (E) extender ended in error.' },
  '%FOUND': { syntax: '%FOUND({file})', summary: '*ON if the last CHAIN, DELETE, SETLL, SETGT, CHECK, SCAN or LOOKUP found a match.' },
  '%HOURS': { syntax: '%HOURS(number)', summary: 'Number of hours as a duration.' },
  '%INT': { syntax: '%INT(expression)', summary: 'Convert to integer (truncates).' },
  '%INTH': { syntax: '%INTH(expression)', summary: 'Convert to integer with half-adjust.' },
  '%KDS': { syntax: '%KDS(data-structure {: number-of-keys})', summary: 'Use the subfields of a data structure as the key list for CHAIN, READE, SETLL...' },
  '%LEN': { syntax: '%LEN(expression {: *MAX})', summary: 'Current length of a value; can be assigned to set the length of a varying field.' },
  '%LIST': { syntax: '%LIST(item1 : item2 ...)', summary: 'Temporary array of values, e.g. for FOR-EACH or IN (IBM i 7.4+).' },
  '%LOOKUP': { syntax: '%LOOKUP(arg : array {: start {: count}})', summary: 'Index of the first element equal to arg (0 if not found). Variants: %LOOKUPLT, LE, GT, GE.' },
  '%LOWER': { syntax: '%LOWER(string {: start {: length}})', summary: 'Convert to lower case (IBM i 7.4+).' },
  '%MAX': { syntax: '%MAX(item1 : item2 ...)', summary: 'Largest of the operands; %MAX(array) gives the index of the maximum element.' },
  '%MIN': { syntax: '%MIN(item1 : item2 ...)', summary: 'Smallest of the operands; %MIN(array) gives the index of the minimum element.' },
  '%MINUTES': { syntax: '%MINUTES(number)', summary: 'Number of minutes as a duration.' },
  '%MONTHS': { syntax: '%MONTHS(number)', summary: 'Number of months as a duration.' },
  '%MSECONDS': { syntax: '%MSECONDS(number)', summary: 'Number of microseconds as a duration.' },
  '%NULLIND': { syntax: '%NULLIND(field)', summary: 'Get or set the null indicator of a null-capable field.' },
  '%OCCUR': { syntax: '%OCCUR(ds)', summary: 'Get or set the current occurrence of a multiple-occurrence data structure.' },
  '%OPEN': { syntax: '%OPEN(file)', summary: '*ON if the file is open.' },
  '%PARMS': { syntax: '%PARMS()', summary: 'Number of parameters passed to the procedure or program.' },
  '%PARMNUM': { syntax: '%PARMNUM(parameter)', summary: 'Ordinal number of a parameter; compare with %PARMS() for optional parameters.' },
  '%RANGE': { syntax: '%RANGE(low : high)', summary: 'Range used with IN, e.g. if x in %RANGE(1:10) (IBM i 7.4+).' },
  '%REM': { syntax: '%REM(n : m)', summary: 'Remainder of n divided by m.' },
  '%REPLACE': { syntax: '%REPLACE(replacement : source {: start {: length}})', summary: 'Replace part of a string.' },
  '%SCAN': { syntax: '%SCAN(search : source {: start {: length}})', summary: 'Position of search in source (0 if not found).' },
  '%SCANR': { syntax: '%SCANR(search : source {: start {: length}})', summary: 'Position of the last occurrence of search in source.' },
  '%SCANRPL': { syntax: '%SCANRPL(search : replacement : source {: start {: length}})', summary: 'Replace every occurrence of search by replacement.' },
  '%SECONDS': { syntax: '%SECONDS(number)', summary: 'Number of seconds as a duration.' },
  '%SIZE': { syntax: '%SIZE(variable {: *ALL})', summary: 'Number of bytes occupied by a variable or data structure.' },
  '%SPLIT': { syntax: '%SPLIT(string {: separators})', summary: 'Split a string into a temporary array of substrings (IBM i 7.4+).' },
  '%STATUS': { syntax: '%STATUS({file})', summary: 'Most recent program or file status code.' },
  '%STR': { syntax: '%STR(pointer {: max-length})', summary: 'Get or store a null-terminated C string at a pointer.' },
  '%SUBARR': { syntax: '%SUBARR(array : start {: count})', summary: 'A section of an array.' },
  '%SUBDT': { syntax: '%SUBDT(value : unit {: digits {: decimals}})', summary: 'Extract a portion (*YEARS, *MONTHS, *DAYS, *HOURS…) of a date, time or timestamp.' },
  '%SUBST': { syntax: '%SUBST(string : start {: length})', summary: 'Substring. Can also be used as the target of an assignment.' },
  '%TIME': { syntax: '%TIME({expression {: format}})', summary: 'Convert to a time value; with no parameters returns the current system time.' },
  '%TIMESTAMP': { syntax: '%TIMESTAMP({expression {: format {: fractional-digits}}})', summary: 'Convert to a timestamp; with no parameters returns the current system timestamp.' },
  '%TLOOKUP': { syntax: '%TLOOKUP(arg : table {: alt-table})', summary: 'Search a table; *ON if found.' },
  '%TRIM': { syntax: "%TRIM(string {: characters})", summary: 'Remove leading and trailing blanks (or the given characters).' },
  '%TRIML': { syntax: "%TRIML(string {: characters})", summary: 'Remove leading blanks (or the given characters).' },
  '%TRIMR': { syntax: "%TRIMR(string {: characters})", summary: 'Remove trailing blanks (or the given characters).' },
  '%UNS': { syntax: '%UNS(expression)', summary: 'Convert to unsigned integer.' },
  '%UPPER': { syntax: '%UPPER(string {: start {: length}})', summary: 'Convert to upper case (IBM i 7.4+).' },
  '%XLATE': { syntax: '%XLATE(from : to : string {: start})', summary: 'Translate characters of string from the "from" list to the "to" list.' },
  '%YEARS': { syntax: '%YEARS(number)', summary: 'Number of years as a duration.' },
};

export const OPCODES: Record<string, DocEntry> = {
  'CTL-OPT': { syntax: 'ctl-opt keywords;', summary: 'Control options (replaces the H spec), e.g. dftactgrp(*no) actgrp(*caller) option(*srcstmt).' },
  'DCL-S': { syntax: 'dcl-s name type {keywords};', summary: 'Declare a standalone field, e.g. dcl-s total packed(11:2) inz;' },
  'DCL-C': { syntax: 'dcl-c name value;', summary: 'Declare a named constant.' },
  'DCL-DS': { syntax: 'dcl-ds name {qualified} {keywords}; … end-ds;', summary: 'Declare a data structure. Use LIKEDS, LIKEREC or EXTNAME to base it on another structure or file.' },
  'DCL-PR': { syntax: 'dcl-pr name {returnType} {extpgm|extproc}; … end-pr;', summary: 'Declare a prototype for a program or procedure call.' },
  'DCL-PI': { syntax: 'dcl-pi {name|*n} {returnType}; … end-pi;', summary: 'Declare the procedure interface (entry parameters) of a program or procedure.' },
  'DCL-PROC': { syntax: 'dcl-proc name {export}; … end-proc;', summary: 'Begin a subprocedure.' },
  'DCL-F': { syntax: 'dcl-f name {device} {usage(*input:*output:*update:*delete)} {keyed};', summary: 'Declare a file (replaces the F spec).' },
  'CHAIN': { syntax: 'chain{(n e)} key file {data-structure};', summary: 'Random read by key or relative record number. Test %FOUND(file) afterwards.' },
  'READ': { syntax: 'read{(n e)} file {data-structure};', summary: 'Read the next record. Test %EOF(file).' },
  'READE': { syntax: 'reade{(n e)} key file {data-structure};', summary: 'Read the next record with an equal key. Test %EOF(file).' },
  'READP': { syntax: 'readp{(n e)} file {data-structure};', summary: 'Read the prior record.' },
  'READPE': { syntax: 'readpe{(n e)} key file {data-structure};', summary: 'Read the prior record with an equal key.' },
  'SETLL': { syntax: 'setll{(e)} key file;', summary: 'Position before the first record with a key ≥ key. %EQUAL tells if an exact match exists.' },
  'SETGT': { syntax: 'setgt{(e)} key file;', summary: 'Position after the last record with a key ≤ key.' },
  'WRITE': { syntax: 'write{(e)} record {data-structure};', summary: 'Write a new record.' },
  'UPDATE': { syntax: 'update{(e)} record {data-structure | %fields(...)};', summary: 'Update the last record read (the record must be locked).' },
  'DELETE': { syntax: 'delete{(e)} {key} file;', summary: 'Delete a record.' },
  'EXFMT': { syntax: 'exfmt{(e)} record-format;', summary: 'Write then read a display file record format.' },
  'IF': { syntax: 'if condition; … {elseif …;} {else;} endif;', summary: 'Conditional block.' },
  'DOW': { syntax: 'dow condition; … enddo;', summary: 'Loop while the condition is true (tested before each iteration).' },
  'DOU': { syntax: 'dou condition; … enddo;', summary: 'Loop until the condition is true (tested after each iteration).' },
  'FOR': { syntax: 'for i = start {to|downto} limit {by step}; … endfor;', summary: 'Counted loop.' },
  'FOR-EACH': { syntax: 'for-each item in array | %list(...) | %split(...); … endfor;', summary: 'Iterate over the elements of an array or list (IBM i 7.4+).' },
  'SELECT': { syntax: 'select; when cond; … other; … endsl;', summary: 'Multi-way branch. Since 7.5 TR: select value; when-is / when-in.' },
  'MONITOR': { syntax: 'monitor; … on-error {status}; … endmon;', summary: 'Handle exceptions raised in the monitored block.' },
  'ON-EXIT': { syntax: 'on-exit {is-abnormal};', summary: 'Code that always runs when a subprocedure ends (IBM i 7.2+).' },
  'BEGSR': { syntax: 'begsr name; … endsr;', summary: 'Begin a subroutine. Prefer subprocedures for new code.' },
  'EXSR': { syntax: 'exsr name;', summary: 'Run a subroutine.' },
  'RETURN': { syntax: 'return {expression};', summary: 'Return from a procedure (with a value) or end the main procedure.' },
  'LEAVE': { syntax: 'leave;', summary: 'Exit the innermost DO/DOW/DOU/FOR loop.' },
  'ITER': { syntax: 'iter;', summary: 'Continue with the next iteration of the innermost loop.' },
  'CLEAR': { syntax: 'clear {*nokey} {*all} name;', summary: 'Set a variable, structure or record format to its default (blanks/zeros).' },
  'RESET': { syntax: 'reset {*nokey} {*all} name;', summary: 'Set a variable back to its initial (INZ) value.' },
  'DSPLY': { syntax: 'dsply message {queue {response}};', summary: 'Display a message (to the job log / *EXT) – handy for quick debugging.' },
  'SORTA': { syntax: 'sorta{(a|d)} array | %subarr(...) | ds(*).subfield;', summary: 'Sort an array.' },
  'DATA-INTO': { syntax: "data-into target %data(doc : options) %parser(parser : options);", summary: 'Parse a document (e.g. JSON with a parser) into a data structure.' },
  'XML-INTO': { syntax: "xml-into target %xml(doc : options);", summary: 'Parse XML into a variable or data structure.' },
  'SND-MSG': { syntax: "snd-msg {*info|*escape} message {%target(...)};", summary: 'Send a program message (IBM i 7.5 TR1 / 7.4 TR7+).' },
  'EXEC': { syntax: 'exec sql statement;', summary: 'Embedded SQL statement (SQLRPGLE sources only).' },
};

export interface ColumnField { from: number; to: number; name: string; hint?: string; }

/** RPG IV fixed-format column layouts (1-based columns). */
export const SPEC_COLUMNS: Record<string, ColumnField[]> = {
  H: [{ from: 6, to: 6, name: 'Form type (H)' }, { from: 7, to: 80, name: 'Control keywords' }],
  F: [
    { from: 6, to: 6, name: 'Form type (F)' }, { from: 7, to: 16, name: 'File name' },
    { from: 17, to: 17, name: 'File type', hint: 'I=input, O=output, U=update, C=combined' },
    { from: 18, to: 18, name: 'File designation', hint: 'P, S, R, T, F or blank' },
    { from: 19, to: 19, name: 'End of file' }, { from: 20, to: 20, name: 'File addition', hint: 'A = records can be added' },
    { from: 21, to: 21, name: 'Sequence' }, { from: 22, to: 22, name: 'File format', hint: 'E=externally described, F=program described' },
    { from: 23, to: 27, name: 'Record length' }, { from: 28, to: 28, name: 'Limits processing' },
    { from: 29, to: 33, name: 'Length of key' }, { from: 34, to: 34, name: 'Record address type', hint: 'K = keyed' },
    { from: 35, to: 35, name: 'File organization' }, { from: 36, to: 42, name: 'Device', hint: 'DISK, WORKSTN, PRINTER, SEQ, SPECIAL' },
    { from: 44, to: 80, name: 'Keywords' },
  ],
  D: [
    { from: 6, to: 6, name: 'Form type (D)' }, { from: 7, to: 21, name: 'Name' },
    { from: 22, to: 22, name: 'External description', hint: 'E = externally described DS' },
    { from: 23, to: 23, name: 'Type of data structure', hint: 'S = program status DS, U = data area DS' },
    { from: 24, to: 25, name: 'Definition type', hint: 'S, C, DS, PR, PI or blank (subfield)' },
    { from: 26, to: 32, name: 'From position' }, { from: 33, to: 39, name: 'To position / Length' },
    { from: 40, to: 40, name: 'Internal data type', hint: 'A, P, S, B, I, U, F, D, T, Z, N, *, G, C' },
    { from: 41, to: 42, name: 'Decimal positions' }, { from: 44, to: 80, name: 'Keywords' },
  ],
  P: [
    { from: 6, to: 6, name: 'Form type (P)' }, { from: 7, to: 21, name: 'Procedure name' },
    { from: 24, to: 24, name: 'Begin / End', hint: 'B or E' }, { from: 44, to: 80, name: 'Keywords' },
  ],
  C: [
    { from: 6, to: 6, name: 'Form type (C)' }, { from: 7, to: 8, name: 'Control level', hint: 'L0-L9, LR, SR, AN/OR' },
    { from: 9, to: 11, name: 'Conditioning indicator', hint: 'e.g. N50 = when *IN50 is off' },
    { from: 12, to: 25, name: 'Factor 1' }, { from: 26, to: 35, name: 'Operation code (and extender)' },
    { from: 36, to: 49, name: 'Factor 2 (extended factor 2: 36-80)' }, { from: 50, to: 63, name: 'Result field' },
    { from: 64, to: 68, name: 'Field length' }, { from: 69, to: 70, name: 'Decimal positions' },
    { from: 71, to: 72, name: 'Resulting indicator HI', hint: 'CHAIN/SETLL: not found' },
    { from: 73, to: 74, name: 'Resulting indicator LO', hint: 'error' },
    { from: 75, to: 76, name: 'Resulting indicator EQ', hint: 'READ: end of file, SETLL: equal' },
    { from: 81, to: 100, name: 'Comment' },
  ],
};
